apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-clone
  template:
    metadata:
      labels:
        app: youtube-clone
    spec:
      containers:
        - name: youtube-clone
          image: your-dockerhub-username/youtube-clone:latest
          ports:
            - containerPort: 80
